### ISSUE TITLE
Bind variable for another IG column in SELECT not populated

### ISSUE THREAD

**Issue by moftot** [Pretius/Pretius-APEX-Enhanced-Lov-Item#53] opened 2020-04-21 11:09 UTC
It appears that a bind variable referring to another IG column in the LOV SELECT isn't populated.

I have two distinct parts of the SELECT, where the part used depends upon a value of another column in the IG on the same row, eg:

`SELECT DISTINCT col1 d,
       col1 r
FROM   tab1
WHERE  :IG_COL1 IN (1, 2)
UNION ALL
SELECT DISTINCT col2 d,
       col2 r
FROM   tab2
WHERE  :IG_COL1 IN (3, 4)
ORDER  BY 1`

I see this in the debug log:

`# Pretius Enhanced LOV Item -> Bind Variable ":IG_COL1" with Value ""`

The column in question is a NUMBER. Is there anything else I need to set for the plug-in to make this work?

**Comment by bostrowski** [comment] 2020-04-26 14:59
Hi @moftot.

Please reproduce the issue at apex.oracle.com using empt and dept table ale send me developer login credentials to ostrowski.bartosz@gmail.com (ws, login, pass).

**Comment by moftot** [comment] 2020-05-05 14:41
Hello

Thanks for your reply. I'm afraid that I don't have access to apex.oracle.com as I'm reluctant to sign up for something "free" that requires a credit card.

However, I've attached an example application that works on SCOTT.EMP. I'm using your plug-in against the JOB column with the following SELECT:

select 'ANALYST' r,
       'ANALYST' d
from   dual
where  :deptno in (10, 20)
union  all
select 'CLERK' r,
       'CLERK' d
from   dual
where  :deptno in (10, 20)
union  all
select 'MANAGER' r,
       'MANAGER' d
from   dual
where  :deptno in (10, 20, 30, 40)
union  all
select 'PRESIDENT' r,
       'PRESIDENT' d
from   dual
where  :deptno in (30, 40)
union  all
select 'SALESMAN' r,
       'SALESMAN' d
from   dual
where  :deptno in (30, 40)

In other words: The values that can be selected are context-specific - they depend upon the value of the DEPTNO column for the same row. ANALYST, CLERK and MANAGER are valid for departments 10 and 20, MANAGER is also valid for departments 30 and 40, PRESIDENT and SALESMAN are valid for departments 30 and 40.

At runtime, when I try to edit JOB (that uses your plug-in) I get the following error in the debug log:

ERR-1002 Unable to find item ID for item "DEPTNO" in application "102".

I've tried assigning a static ID DEPTNO to the DEPTNO item, to no avail.

So in this case I don't even get to your plug-in trying to bind a value as it can't find the application item.

What am I missing here? Do I need to set up something submitting the correct value to the server? It this at all possible?

Thanks a lot for your help.

Best regards

**Comment by bostrowski** [comment] 2020-05-05 15:17
@moftot 

I insist on reproducing the issue at apex.oracle.com which is totaly free and doesn't require credit card to create free workspace. You ended up in registration form for Oracle Cloud service.

You can request free workspace here:

![image](https://user-images.githubusercontent.com/15342508/81082203-40962400-8ef3-11ea-88ac-d247235b4a7e.png)

![image](https://user-images.githubusercontent.com/15342508/81082278-5ad00200-8ef3-11ea-8606-7ef9d4016e3d.png)

or using link from here

![image](https://user-images.githubusercontent.com/15342508/81082904-2e68b580-8ef4-11ea-87ee-82273c7e0ea1.png)

I've tested cascading lov in ig. Its not perfect but it works.
![enhanced_lov_item_example_cascading_lov](https://user-images.githubusercontent.com/15342508/81082669-de89ee80-8ef3-11ea-84b2-7d41794f0a0f.gif)

Please reproduce your issue at apex.oracle.com

**Comment by moftot** [comment] 2020-05-26 07:26
I PM'ed you the required info on 07 May 2020, have you had a chance to look at it?

Thanks.

**Comment by bostrowski** [comment] 2020-05-26 10:49
Hi, sorry for very delayed answer. Good that you have reminded me the issue - the case is that I'm no longer Pretius employee and I'm supporting my (Pretius) plug-ins in free time. Sorry for inconveniences.

Regarding the issue. I've checked your implementation and the case is that you are using bind variable `:deptno` in SQL query for column **JOB** without letting APEX know that this column is dependent on column **DEPTNO**. This relation is called **Cascading LOV** and it **requires** setting **Cascading List of Values \ Parent Column(s)** for column that is dependent.

I've copied your example home page (home copy, page 2) and set the cascading lov:

![image](https://user-images.githubusercontent.com/15342508/82890704-e36b1c80-9f4c-11ea-9970-33ff6540ddab.png)

In your implementation the plug-in popup report returned 0 rows (because value of deptno from row is not set in session) and after setting cascading lov it the plug-in popup returns jobs depending on DEPTNO value (your conditional SQL query for column job).

Without cascading lov:
![without_cascading_lov](https://user-images.githubusercontent.com/15342508/82891794-a56ef800-9f4e-11ea-8c04-e2be2853e805.gif)

With cascading lov:
![with_cascading_lov](https://user-images.githubusercontent.com/15342508/82891821-b15aba00-9f4e-11ea-8f76-14f18147f206.gif)

This is not the plug-in issue nor bug.

Please, let me know whether that was the "issue". If yes I will close this thread.

**Comment by moftot** [comment] 2020-05-26 11:12
Excellent, thanks a lot.

I hoped it would be something as simple as that.

This solves the "issue". Thanks for your help.

**Closed** 2020-05-26 11:12 UTC
